version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/actions/*'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
    open-pull-requests-limit: 10
