version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/actions/*'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    groups:
      minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependencies'
      - 'github_actions'
    open-pull-requests-limit: 10
  - package-ecosystem: 'bun'
    directories:
      - '/'
      - '/actions/validate-docs-tree'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    groups:
      minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
