name: Self / Dependabot

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/ops-dependabot.yml
