name: Self / Dependabot

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: read

jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
      checks: read
      actions: read
    uses: $/.github/workflows/ops-dependabot.yml
