name: Self / Release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  release:
    if: github.ref_type == 'tag' && contains(github.ref_name, '.')
    permissions:
      contents: write
    uses: $/.github/workflows/release.yml
