name: Self / Dependabot

on:
  pull_request:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/ops-dependabot.yml
